const getUserCartQuery = (id) => `
SELECT PRODUCTS.NAME AS 'name', (INVENTORIES.AMOUNT >= CARTS.QUANTITY)  AS 'isValid',
	COLORS.NAME AS 'color', COLORS.HEX AS 'hex', SIZES.NAME AS 'size', CARTS.QUANTITY AS 'quantity',
    INVENTORIES.AMOUNT AS 'amount', json_arrayagg( IMAGES.URL) as 'images',
    INVENTORIES.ID AS 'inventoryId', PRODUCTS.ID AS 'productId', PRODUCTS.PRICE AS 'price'
FROM USERS, CARTS, INVENTORIES, PRODUCTS, SIZES, COLORS, IMAGES
WHERE USERS.id = ${id} AND USERS.ID = CARTS.userId AND CARTS.INVENTORYID = INVENTORIES.ID
	AND PRODUCTS.ID = INVENTORIES.PRODUCTID AND SIZES.ID = INVENTORIES.SIZEID 
    AND COLORS.ID = INVENTORIES.COLORID AND IMAGES.PRODUCTID = PRODUCTS.ID
GROUP BY PRODUCTS.NAME, COLORS.NAME, COLORS.HEX, SIZES.NAME, CARTS.QUANTITY, INVENTORIES.AMOUNT,
	INVENTORIES.ID
`

module.exports = { getUserCartQuery }
