const userTypes = {
	LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
	LOAD_USER_ERROR: 'LOAD_USER_ERROR',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
	LOGOUT_USER: 'LOGOUT_USER',
	CHANGE_USER_INFO: 'CHANGE_USER_INFO',
}

export default userTypes
