const userTypes = {
	LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
	LOAD_USER_ERROR: 'LOAD_USER_ERROR',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
	SET_VERIFICATION_EMAIL: 'SET_VERIFICATION_EMAIL',
	RESEND_VERIFICATION_EMAIL_SUCCESS: 'RESEND_VERIFICATION_EMAIL_SUCCESS',
	LOGOUT_USER: 'LOGOUT_USER',
}

export default userTypes
