const productTypes = {
	GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
	GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
	SET_SHOW_PRODUCT_MODAL: 'SET_SHOW_PRODUCT_MODAL',
	SET_IS_LOADING_PRODUCT_MODAL: 'SET_IS_LOADING_PRODUCT_MODAL',
	SET_PRODUCT_MODEL: 'SET_PRODUCT_MODEL',
}

export default productTypes
