const productTypes = {
	SET_PRODUCTS: 'SET_PRODUCTS',
	SET_PRODUCT: 'SET_PRODUCT',
	SET_SHOW_PRODUCT_MODAL: 'SET_SHOW_PRODUCT_MODAL',
	SET_IS_LOADING_PRODUCT_MODAL: 'SET_IS_LOADING_PRODUCT_MODAL',
	SET_PRODUCT_MODEL: 'SET_PRODUCT_MODEL',
}

export default productTypes
